server:
  connection-timeout: 8000
  tomcat:
    uri-encoding: utf-8
    max-connections: 1000
    max-threads: 200
    min-spare-threads: 10
  port: 8080

spring:
  profiles:
    active: pro,pro_redis,pro_mysql,pro_log4j2 #加载多个模块配置文件yml



