#正式使用 不独立配置的模块
quartz:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://39.106.111.11:3306/walker?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: walker
    password: qwer
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      #自动创建表
      ddl-auto: update
      #jpa表名大小写问题 全大写
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 39.106.111.11
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 8000

    default:
      #redis cache 过期时间
      expiration:3600

logging:
  file: /home/walker/logs/sb.log
  #  pattern:
  #    console: "%date{HH:mm:ss.SSS} %-5level %-30.30logger{29} : %msg%n"
  Root:
    level: debug
    AppenderRef:
      - ref: CONSOLE
      - ref: ROLLING_FILE
  level:
    com.demo: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG


#
#logging:
#  config: classpath:log4j2.yml


