spring:
  datasource:
    url: jdbc:mysql://39.106.111.11:3306/walker?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: walker
    password: qwer
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      #自动创建表
      ddl-auto: update
      #jpa表名大小写问题 全大写
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#prefix=spring.resources, ignoreInvalidFields=false, ignoreUnknownFields=false; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.resources' to org.springframework.boot.autoconfigure.web.ResourceProperties
#2019-07-22 14:35:32.864  INFO 30039 --- [  restartedMain] ConditionEvaluationReportLoggingListener :
  resources:
    static-locations: classpath:/
#    redis:
#      timeout: 3000
#      host: 127.0.0.1
#      password:
#      sentinel:
#        master: master
#        nodes: xxx,xxx,xxx
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 4
#          max-wait: 100



#
#logging:
#  config: classpath:log4j2.yml