#正式使用 不独立配置的模块
quartz:
  enabled: true
spring:
#指定别名数据源
#spring.datasource.walker.url=jdbc:mysqlxxxx
#默认主数据源 改到sharding里统一路由
#  datasource:
#    url: jdbc:mysql://39.106.111.11:3306/walker?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: walker
#    password: qwer
##    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    tomcat:
#      max-idle: 4
#      max-wait: 4
#      max-active: 64
#      validation-query: select 1 from dual
#      validation-query-timeout: 1000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      #自动创建表
      ddl-auto: update
      #jpa表名大小写问题 全大写
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect  #分表合表MERGE引擎依赖myisam
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎

  #
  #mybatis:
  #  mapper-locations: classpath:mybatis/mapper/*.xml
  #  type-aliases-package: com.sun.shard.bean

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 39.106.111.11
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 8000

    default:
      #redis cache 过期时间
      expiration:3509

  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: service-provider
      id: service-provider
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
#      address: redis://39.106.111.11:6379
    #    server: true

    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    scan: com.walker.service.impl  #服务暴露与发现消费所在的package




logging:
  file: /home/walker/logs/sb.log
  #  pattern:
  #    console: "%date{HH:mm:ss.SSS} %-5level %-30.30logger{29} : %msg%n"
  Root:
    level: debug
    AppenderRef:
      - ref: CONSOLE
      - ref: ROLLING_FILE
  level:
    com.demo: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

#
#logging:
#  config: classpath:log4j2.yml


