spring:
  datasource:
    url: jdbc:mysql://39.106.111.11:3306/walker?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: walker
    password: qwer
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
