#本地数据库 本地redis等配置 调试用

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8098/walker?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: walker
    password: qwer
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      #自动创建表
      ddl-auto: update
      #jpa表名大小写问题 全大写
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  resources:
    static-locations: classpath:/



  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password: qwer
    # Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最小空闲连接
        min-idle: 1
    # 连接超时时间（毫秒）
    timeout: 8000

#
logging:
  file: classpath:log4j2.yml